repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.2
    hooks:
    -   id: gofumpt # requires github.com/mvdan/gofumpt
    -   id: golangci-lint # requires github.com/golangci/golangci-lint
